### ISSUE TITLE
运行没有反映阿

### ISSUE THREAD

**Issue by ucitx** [Holmose/yngbwscript#1]
本地启动 WebDriver 成功，开始执行脚本
Server stared on 192.168.100.72:9999

就没了

**Comment by Holmose** [comment]
需要安装 aibot 环境

**Comment by Holmose** [comment]
下载并安装好http://www.aibote.net/download.html，并且需要安装对应浏览器，代码中是chrome 浏览器，也可以切换的，chrome 浏览器下载的得是官方版本的

**Comment by ucitx** [comment]
你说的这两个都已经安装了

**Comment by ucitx** [comment]
现在好象只能学习必学课件，希望更新一下能学习选学课件

**Comment by Holmose** [comment]
已更新
